//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLTDABD_Rel.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLTDABD_Rel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon _as {
            get {
                object obj = ResourceManager.GetObject("_as", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   #version 140
        ///
        ///in vec3 normal;
        ///
        ///out vec4 outputColor;
        ///
        ///void main()
        ///{
        ///	vec3 unitNormal = normalize(normal);
        ///	float nDotProduct = clamp(dot(unitNormal, vec3(0.707, 0, 0.707)), 0, 1);
        ///	vec2 ContributionWeightsSqrt = vec2(0.5, 0.5f) + vec2(0.5f, -0.5f) * unitNormal.y;
        ///	vec2 ContributionWeights = ContributionWeightsSqrt * ContributionWeightsSqrt;
        ///
        ///	vec3 color = nDotProduct * vec3(1, 0.957, 0.839) / 3.14159;
        ///	color += vec3(0.779, 0.716, 0.453) * ContributionWeights.y;
        ///	color += vec3(0.368, 0.477, 0.735) * Contribu [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fs {
            get {
                return ResourceManager.GetString("fs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #version 140
        ///
        ///out vec4 outputColor;
        ///
        ///void main()
        ///{
        ///	outputColor = vec4(0, 0, 0, 1);
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fsBlack {
            get {
                return ResourceManager.GetString("fsBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #version 140
        ///
        ///out vec4 outputColor;
        ///in vec4 color;
        ///
        ///void main()
        ///{
        ///	outputColor = color;
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fsColor {
            get {
                return ResourceManager.GetString("fsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap preview {
            get {
                object obj = ResourceManager.GetObject("preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   #version 140
        ///
        ///in vec3 vertexPosition;
        ///in vec3 normalDirection;
        ///in vec4 vertexColor;
        ///uniform mat4 modelMatrix;
        ///uniform mat4 viewMatrix;
        ///uniform mat4 projMatrix;
        ///
        ///out vec3 normal;
        ///out vec4 color;
        ///
        ///void main()
        ///{
        ///	gl_Position = projMatrix * viewMatrix * modelMatrix * vec4(vertexPosition, 1.0);
        ///	normal = normalDirection;
        ///	color = vertexColor; 
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string vs {
            get {
                return ResourceManager.GetString("vs", resourceCulture);
            }
        }
    }
}
